version: "3.9"
name: project-layout-dev

services:
  event-api:
    build:
      context: ../../.
      dockerfile: deploy/dev/Dockerfile-event-api
    image: events_api
    container_name: project-layout-dev-event-api
    ports:
      - "8080:8080"
    networks:
      - project-layout-dev-infrastructure-network

networks:
  project-layout-dev-infrastructure-network:
    name: project-layout-dev-infrastructure-network
    external: true