FROM golang:1.22.2-alpine AS build

ENV GOPATH="" CGO_ENABLED=0

COPY go.mod go.mod
COPY go.sum go.sum
COPY cmd/service-a cmd/service-a
COPY internal internal

RUN go mod download
RUN go build -o /bin/app cmd/service-a/main.go

FROM alpine:3.20.1

COPY --from=build /bin/app /app/
COPY configs/dev/service-a.config.json /app/config.json

WORKDIR /app/
EXPOSE 8080

CMD ["./app", "-c=config.json"]
