version: "3.9"
name: project-layout-dev-infrastructure

services:
  mysql:
    image: mysql:8.0
    container_name: project-layout-dev-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=testdb
    ports:
      - "3306:3306"
    networks:
      - project-layout-dev-infrastructure-network
    volumes:
      - ../../../../project-layout-infrastructure/dev/volumes/mysql:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  redis:
    image: redis:7.0
    container_name: project-layout-dev-redis
    ports:
      - "6379:6379"
    networks:
      - project-layout-dev-infrastructure-network

  clickhouse:
    image: clickhouse/clickhouse-server:22.11.2
    container_name: project-layout-dev-clickhouse
    environment:
      - CLICKHOUSE_DB=testdb
      - CLICKHOUSE_USER=test
      - CLICKHOUSE_PASSWORD=test
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "9000:9000"
      - "8123:8123"
    networks:
      - project-layout-dev-infrastructure-network
    volumes:
      - ../../../../project-layout-infrastructure/dev/volumes/clickhouse/data:/var/lib/clickhouse
      - ../../../../project-layout-infrastructure/dev/volumes/clickhouse/logs:/var/log/clickhouse-server

  tarantool:
    image: tarantool/tarantool:2.11.3-ubuntu20.04
    container_name: project-layout-dev-tarantool
    ports:
      - "3301:3301"
    networks:
      - project-layout-dev-infrastructure-network
    volumes:
      - ../../../scripts/tarantool/init.lua:/opt/tarantool/init.lua
      - ../../../scripts/tarantool/spaces.lua:/usr/local/share/tarantool/spaces.lua
      - ../../../../project-layout-infrastructure/dev/volumes/tarantool:/var/lib/tarantool
    command: [ 'tarantool', '/opt/tarantool/init.lua' ]

  nats:
    image: nats:2.9-alpine
    container_name: project-layout-dev-nats
    ports:
      - "4222:4222"
    networks:
      - project-layout-dev-infrastructure-network

networks:
  project-layout-dev-infrastructure-network:
    name: project-layout-dev-infrastructure-network
    driver: bridge